# Generated by Django 4.2.30 on 2026-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
