# Generated by Django 4.2.5 on 2023-09-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='diseases',
            field=models.ManyToManyField(related_name='+', to='diseases.disease'),
        ),
    ]
