# Generated by Django 2.0.1 on 2018-01-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='human_size',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='status',
            field=models.CharField(max_length=300),
        ),
    ]
