# Generated by Django 4.2.6 on 2023-10-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sample_description_sample_location'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='samples',
            field=models.ManyToManyField(blank=True, to='samples.sample'),
        ),
    ]
