# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('projects', '0002_auto_20170822_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='project_groups', to='auth.Group'),
        ),
    ]
