# Generated by Django 2.0.1 on 2018-01-17 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20180116_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, null=True)),
                ('prefix', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('alias', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('human_size', models.CharField(max_length=300)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('file_type', models.TextField(blank=True, null=True)),
                ('md5', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('n_files', models.IntegerField(blank=True, default=0, null=True)),
                ('sum_filesize', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('has_fastq', models.BooleanField(default=False)),
                ('n_fastqs', models.IntegerField(blank=True, default=0, null=True)),
                ('has_bam', models.BooleanField(default=False)),
                ('n_bams', models.IntegerField(blank=True, default=0, null=True)),
                ('has_vcf', models.BooleanField(default=False)),
                ('n_vcfs', models.IntegerField(blank=True, default=0, null=True)),
                ('has_all', models.BooleanField(default=False)),
                ('files', models.ManyToManyField(blank=True, to='projects.ProjectFile')),
                ('project', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
