# Generated by Django 2.0 on 2017-12-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, to='projects.File'),
        ),
    ]
