# Generated by Django 2.0 on 2017-12-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171231_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
