# Generated by Django 2.0.1 on 2018-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectsample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsample',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='projectsample',
            name='has_all',
        ),
        migrations.RemoveField(
            model_name='projectsample',
            name='has_bam',
        ),
        migrations.RemoveField(
            model_name='projectsample',
            name='has_fastq',
        ),
        migrations.RemoveField(
            model_name='projectsample',
            name='has_vcf',
        ),
        migrations.RemoveField(
            model_name='projectsample',
            name='human_size',
        ),
        migrations.RemoveField(
            model_name='projectsample',
            name='md5',
        ),
        migrations.RemoveField(
            model_name='projectsample',
            name='size',
        ),
        migrations.RemoveField(
            model_name='projectsample',
            name='sum_filesize',
        ),
        migrations.AlterField(
            model_name='projectsample',
            name='status',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
