# Generated by Django 2.0 on 2018-01-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180108_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
