# Generated by Django 2.0 on 2018-01-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20180108_2352'),
        ('projects', '0008_auto_20180108_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
    ]
