#!/bin/bash

if [ $1 = "install" ] ; then
 
    pip install cython
    pip install pynnotator
    pynnotator install
    pip install -r mendelmd_source/requirements.stable.txt 

fi


#check if repository exists
# git clone https://raonyguimaraes@bitbucket.org/raonyguimaraes/mendelmd

# cd mendelmd

# sudo apt-get install python-pip
# sudo pip install virtualenvwrapper
# source virtualenvwrapper.sh

# #check if folder exists
# mkvirtualenv mendelmd_prod

# #run annotator install.py

# pip install -r requirements.txt
# python manage.py syncdb #create superuser
# python manage.py runserver #run devserver

# #For production you need to use 
