# Generated by Django 4.2.5 on 2023-10-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapps', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('repository', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name_plural': 'analysis_types',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('status', models.TextField(blank=True, null=True)),
                ('apps', models.ManyToManyField(to='mapps.app')),
                ('files', models.ManyToManyField(to='files.file')),
            ],
            options={
                'verbose_name_plural': 'analyses',
            },
        ),
    ]
