# Generated by Django 2.0.1 on 2018-02-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapps', '0003_auto_20180218_1534'),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='apps',
            field=models.ManyToManyField(to='mapps.App'),
        ),
    ]
