# Generated by Django 4.2.5 on 2023-10-03 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='samples',
            field=models.ManyToManyField(to='samples.sample'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='tasks',
            field=models.ManyToManyField(to='tasks.task'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
