# Generated by Django 2.0.1 on 2018-02-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180204_0207'),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='tasks',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
