# Generated by Django 2.0.1 on 2018-01-31 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_auto_20180131_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='type',
        ),
    ]
