# Generated by Django 2.0.1 on 2018-02-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_analysis_samples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='user',
        ),
    ]
