# Generated by Django 2.0.1 on 2018-01-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_samplegroup'),
        ('analyses', '0003_auto_20180131_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='samples',
            field=models.ManyToManyField(to='samples.Sample'),
        ),
    ]
