# Generated by Django 2.0.1 on 2018-01-31 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_sample_files'),
        ('analyses', '0003_auto_20180131_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='samples',
            field=models.ManyToManyField(blank=True, null=True, to='samples.Sample'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
