# Generated by Django 2.0.1 on 2018-01-31 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_auto_20180131_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='samples',
            field=models.ManyToManyField(to='samples.Sample'),
        ),
    ]
