# Generated by Django 2.0.1 on 2018-01-31 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_analysis_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
