# Generated by Django 2.0.1 on 2018-01-31 21:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_auto_20180131_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
