# Generated by Django 2.0.1 on 2018-02-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0006_auto_20180201_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
