# Generated by Django 2.0.1 on 2018-02-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0007_analysis_status'),
        ('analyses', '0006_auto_20180131_2156'),
    ]

    operations = [
    ]
