# Generated by Django 2.0.1 on 2018-02-12 19:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0008_remove_analysis_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
