# Generated by Django 2.0.1 on 2018-02-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0009_analysis_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='status',
        ),
    ]
