# Generated by Django 2.0.1 on 2018-02-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0010_remove_analysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
