# Generated by Django 2.0.1 on 2018-02-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0011_analysis_status'),
        ('analyses', '0002_analysis_tasks'),
    ]

    operations = [
    ]
