# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='shared_with',
            new_name='shared_with_users',
        ),
        migrations.AddField(
            model_name='case',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_with', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='case_groups', to='auth.Group', verbose_name='Groups of Cases'),
        ),
        migrations.AlterField(
            model_name='case',
            name='cases',
            field=models.ManyToManyField(blank=True, null=True, related_name='cases', to='individuals.Individual'),
        ),
        migrations.AlterField(
            model_name='case',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='individuals.Individual'),
        ),
        migrations.AlterField(
            model_name='case',
            name='control_groups',
            field=models.ManyToManyField(blank=True, related_name='control_groups', to='auth.Group', verbose_name='Groups of Controls'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to='individuals.Individual'),
        ),
        migrations.AlterField(
            model_name='case',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='individuals.Individual'),
        ),
    ]
