# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20170829_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_groups',
            field=models.ManyToManyField(blank=True, related_name='case_groups', to='auth.Group', verbose_name='Groups of Cases'),
        ),
        migrations.AlterField(
            model_name='case',
            name='cases',
            field=models.ManyToManyField(blank=True, related_name='cases', to='individuals.Individual'),
        ),
        migrations.AlterField(
            model_name='case',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='children', to='individuals.Individual'),
        ),
    ]
