# Generated by Django 2.1.4 on 2018-12-06 14:06

from django.db import migrations
from django.core.management import call_command


def add_products(apps, schema_editor):
    call_command('loaddata', 'product', app_label='ecommerce_app')


def remove_products(apps, schema_editor):
    Product = apps.get_model('ecommerce_app', 'Product')

    Product.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_product_is_subscription'),
    ]

    operations = [
        # migrations.RunPython(add_products, remove_products)
    ]
