# Generated by Django 2.0.2 on 2018-03-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleVariantGenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variants.Genotype')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_index', models.TextField(db_index=True)),
                ('chr', models.TextField(db_index=True, verbose_name='Chr')),
                ('pos', models.IntegerField(db_index=True)),
                ('variant_id', models.TextField(db_index=True, verbose_name='ID')),
                ('ref', models.TextField(blank=True, db_index=True, null=True)),
                ('alt', models.TextField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variants.Variant')),
            ],
        ),
        migrations.AddField(
            model_name='samplevariantgenotype',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variants.Variant'),
        ),
    ]
