# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-05 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='index',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
