# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-05 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_auto_20171005_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='index',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
