# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegg', models.CharField(max_length=255)),
                ('name', models.TextField(blank=True, null=True)),
                ('genes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
