# Generated by Django 4.2.6 on 2023-10-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pathway",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kegg", models.CharField(max_length=255)),
                ("name", models.TextField(blank=True, null=True)),
                ("genes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
