# Generated by Django 4.0 on 2021-12-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='params',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='config',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='config',
            field=models.JSONField(),
        ),
    ]
