# Generated by Django 2.0.1 on 2018-02-05 23:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
            preserve_default=False,
        ),
    ]
