# Generated by Django 4.2.6 on 2023-10-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("desc", models.TextField()),
                ("provider", models.CharField(max_length=30)),
                ("ip", models.CharField(max_length=30)),
            ],
        ),
    ]
