# Generated by Django 4.2.6 on 2023-10-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("url", models.CharField(blank=True, max_length=30, null=True)),
                ("username", models.CharField(blank=True, max_length=300, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                ("cost", models.FloatField(blank=True, default=0, null=True)),
                ("desc", models.CharField(blank=True, max_length=300, null=True)),
                ("status", models.CharField(blank=True, max_length=300, null=True)),
                ("usage", models.CharField(blank=True, max_length=300, null=True)),
                ("cpu_load", models.CharField(blank=True, max_length=300, null=True)),
                ("provider", models.CharField(blank=True, max_length=300, null=True)),
                ("ip", models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
