# Generated by Django 4.2.6 on 2023-10-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
