# Generated by Django 4.2.6 on 2023-10-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="cpu_load",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="password",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="desc",
            field=models.TextField(null=True),
        ),
    ]
