# Generated by Django 4.2.6 on 2023-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_server_cpu_load_server_password_alter_server_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="status",
            field=models.TextField(null=True),
        ),
    ]
