# Generated by Django 4.2.6 on 2023-10-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='usage',
            field=models.TextField(null=True),
        ),
    ]
