# Generated by Django 4.2.6 on 2023-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0004_server_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="url",
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="server",
            name="username",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="cpu_load",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="desc",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="ip",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="provider",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="status",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="usage",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
