# Generated by Django 4.2.6 on 2023-10-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0005_server_url_server_username_alter_server_cpu_load_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="cost",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="cpu_load",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="desc",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="ip",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="provider",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="usage",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
