# Generated by Django 4.2.6 on 2023-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "servers",
            "0006_server_cost_alter_server_cpu_load_alter_server_desc_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="url",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="usage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
