# Generated by Django 4.2.6 on 2023-10-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0007_alter_server_url_alter_server_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="cpu_load",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="desc",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="ip",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="provider",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="status",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="usage",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="username",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
