# Generated by Django 2.1.1 on 2019-03-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_variant_snpeff_func_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='snpeff_codon_change',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
