version: '2'
services:
 db:
   image: postgres
   volumes:
     - ./data/postgresql_data:/var/lib/postgresql/data/
   restart: always

 web:
   image: raonyguimaraes/mendelmd
   command: bash docker-entrypoint.sh
   volumes:
     #- .:/code
     - ./data:/usr/local/lib/python3.6/dist-packages/pynnotator/pynnotator/data
   ports:
     - "8000:8000"
   depends_on:
     - db
     
    
 # annotator:
 #  build: ./compose/annotator
