# Generated by Django 2.0.1 on 2018-02-18 15:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapps', '0002_auto_20180217_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
