# Generated by Django 2.0.1 on 2018-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapps', '0004_app_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='install',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='main',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
