# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='retry',
            field=models.IntegerField(default=0),
        ),
    ]
