# Generated by Django 4.2.6 on 2023-10-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_taken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
