# Generated by Django 2.0.1 on 2018-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
