# Generated by Django 2.0.1 on 2018-02-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_params'),
        ('tasks', '0002_task_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(to='files.File'),
        ),
    ]
