# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
        ('tasks', '0003_auto_20170901_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='individuals',
            field=models.ManyToManyField(to='individuals.Individual'),
        ),
    ]
