# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_individuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(max_length=600),
        ),
    ]
