# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20170904_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='machine',
            field=models.CharField(default=0, max_length=600),
            preserve_default=False,
        ),
    ]
