# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('size', models.TextField(blank=True, null=True)),
                ('file_type', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('local_file', models.FileField(blank=True, help_text='File Format: VCF', max_length=600, upload_to=files.models.File.get_upload_path)),
                ('status', models.TextField(blank=True, null=True)),
                ('md5', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
