# Generated by Django 2.0.1 on 2018-01-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
