# Generated by Django 2.1.7 on 2019-04-05 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AddField(
            model_name='file',
            name='users',
            field=models.ManyToManyField(editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
