# Generated by Django 2.0 on 2018-01-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_delete_s3credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='file',
            name='human_size',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='remote_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
