# Generated by Django 2.0.1 on 2018-02-18 12:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
