# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_s3credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
