# Generated by Django 2.0.1 on 2018-01-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
