# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20170823_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3credential',
            name='exclude_files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s3credential',
            name='exclude_paths',
            field=models.TextField(blank=True, null=True),
        ),
    ]
