# Generated by Django 2.1.7 on 2019-04-05 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0003_auto_20190405_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='users',
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
