# Generated by Django 2.0.1 on 2018-02-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20180130_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='human_size',
        ),
    ]
