# Generated by Django 2.0 on 2018-01-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='human_size',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
