# Generated by Django 2.1.7 on 2019-04-08 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20190405_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCF',
            fields=[
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='files.File')),
                ('n_samples', models.IntegerField(blank=True, null=True)),
                ('n_header', models.BigIntegerField(blank=True, null=True)),
                ('n_variants', models.BigIntegerField(blank=True, null=True)),
                ('build', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
