# Generated by Django 2.1.7 on 2019-04-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_vcf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcf',
            name='file',
        ),
        migrations.DeleteModel(
            name='VCF',
        ),
    ]
