# Generated by Django 4.0 on 2021-12-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20190428_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
