# Generated by Django 2.1.1 on 2019-03-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='snpeff_func_class',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
