# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
        migrations.AlterField(
            model_name='project',
            name='individuals',
            field=models.ManyToManyField(blank=True, to='individuals.Individual'),
        ),
    ]
