# Generated by Django 4.2.6 on 2023-10-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("key", models.TextField(blank=True)),
                ("host", models.CharField(blank=True, max_length=200)),
                ("username", models.CharField(blank=True, max_length=200)),
                ("password", models.CharField(blank=True, max_length=200)),
                (
                    "cloudprovider",
                    models.CharField(
                        choices=[
                            ("Hetzner", "Hetzner"),
                            ("Google", "Google"),
                            ("AWS", "AWS"),
                            ("Cpanel", "Cpanel"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSHKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("key", models.TextField()),
            ],
        ),
    ]
