# Generated by Django 4.2.6 on 2023-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudkey',
            name='host',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudkey',
            name='password',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudkey',
            name='username',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloudkey',
            name='cloudprovider',
            field=models.CharField(choices=[('Hetzner', 'Hetzner'), ('Google', 'Google'), ('AWS', 'AWS'), ('Cpanel', 'Cpanel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cloudkey',
            name='key',
            field=models.TextField(blank=True),
        ),
    ]
