# Generated by Django 4.2.6 on 2023-10-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_cloudkey_host_cloudkey_password_cloudkey_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudkey',
            name='host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cloudkey',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cloudkey',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
