# Generated by Django 4.2.6 on 2023-10-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("data", models.JSONField(blank=True, null=True)),
                ("server", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
