# Generated by Django 4.2.6 on 2023-10-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
