# Generated by Django 2.0.1 on 2018-01-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='prefix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
