# Generated by Django 2.0.1 on 2018-01-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20180130_0940'),
        ('samples', '0002_sample_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
    ]
