# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genomes1K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr', models.CharField(db_index=True, max_length=2)),
                ('pos', models.IntegerField(db_index=True)),
                ('ref', models.CharField(db_index=True, max_length=2)),
                ('alt', models.CharField(db_index=True, max_length=255)),
                ('qual', models.FloatField(db_index=True)),
                ('filter', models.CharField(db_index=True, max_length=255)),
                ('info', models.CharField(db_index=True, max_length=255)),
                ('format', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
